// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: ha.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Hb
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_ha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_ha_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetHb() int32 {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Hb); ok {
			return x.Hb
		}
	}
	return 0
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Hb struct {
	Hb int32 `protobuf:"varint,1,opt,name=hb,proto3,oneof"`
}

func (*ClientMessage_Hb) isClientMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Hb
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_ha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_ha_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetHb() int32 {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Hb); ok {
			return x.Hb
		}
	}
	return 0
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Hb struct {
	Hb int32 `protobuf:"varint,1,opt,name=hb,proto3,oneof"`
}

func (*ServerMessage_Hb) isServerMessage_Payload() {}

var File_ha_proto protoreflect.FileDescriptor

const file_ha_proto_rawDesc = "" +
	"\n" +
	"\bha.proto\x12\x05ha_pb\",\n" +
	"\rClientMessage\x12\x10\n" +
	"\x02hb\x18\x01 \x01(\x05H\x00R\x02hbB\t\n" +
	"\apayload\",\n" +
	"\rServerMessage\x12\x10\n" +
	"\x02hb\x18\x01 \x01(\x05H\x00R\x02hbB\t\n" +
	"\apayload2J\n" +
	"\tHAService\x12=\n" +
	"\vHAStreaming\x12\x14.ha_pb.ClientMessage\x1a\x14.ha_pb.ServerMessage(\x010\x01B\x18Z\x16kenmec/ha/protoGen;genb\x06proto3"

var (
	file_ha_proto_rawDescOnce sync.Once
	file_ha_proto_rawDescData []byte
)

func file_ha_proto_rawDescGZIP() []byte {
	file_ha_proto_rawDescOnce.Do(func() {
		file_ha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ha_proto_rawDesc), len(file_ha_proto_rawDesc)))
	})
	return file_ha_proto_rawDescData
}

var file_ha_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ha_proto_goTypes = []any{
	(*ClientMessage)(nil), // 0: ha_pb.ClientMessage
	(*ServerMessage)(nil), // 1: ha_pb.ServerMessage
}
var file_ha_proto_depIdxs = []int32{
	0, // 0: ha_pb.HAService.HAStreaming:input_type -> ha_pb.ClientMessage
	1, // 1: ha_pb.HAService.HAStreaming:output_type -> ha_pb.ServerMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ha_proto_init() }
func file_ha_proto_init() {
	if File_ha_proto != nil {
		return
	}
	file_ha_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Hb)(nil),
	}
	file_ha_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Hb)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ha_proto_rawDesc), len(file_ha_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ha_proto_goTypes,
		DependencyIndexes: file_ha_proto_depIdxs,
		MessageInfos:      file_ha_proto_msgTypes,
	}.Build()
	File_ha_proto = out.File
	file_ha_proto_goTypes = nil
	file_ha_proto_depIdxs = nil
}
