// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: ha.proto

package gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HAService_HAStreaming_FullMethodName = "/ha_pb.HAService/HAStreaming"
)

// HAServiceClient is the client API for HAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// bidirectional Streaming
type HAServiceClient interface {
	// bidirectional Streaming
	HAStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type hAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHAServiceClient(cc grpc.ClientConnInterface) HAServiceClient {
	return &hAServiceClient{cc}
}

func (c *hAServiceClient) HAStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HAService_ServiceDesc.Streams[0], HAService_HAStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HAService_HAStreamingClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// HAServiceServer is the server API for HAService service.
// All implementations must embed UnimplementedHAServiceServer
// for forward compatibility.
//
// bidirectional Streaming
type HAServiceServer interface {
	// bidirectional Streaming
	HAStreaming(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedHAServiceServer()
}

// UnimplementedHAServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHAServiceServer struct{}

func (UnimplementedHAServiceServer) HAStreaming(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method HAStreaming not implemented")
}
func (UnimplementedHAServiceServer) mustEmbedUnimplementedHAServiceServer() {}
func (UnimplementedHAServiceServer) testEmbeddedByValue()                   {}

// UnsafeHAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HAServiceServer will
// result in compilation errors.
type UnsafeHAServiceServer interface {
	mustEmbedUnimplementedHAServiceServer()
}

func RegisterHAServiceServer(s grpc.ServiceRegistrar, srv HAServiceServer) {
	// If the following call panics, it indicates UnimplementedHAServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HAService_ServiceDesc, srv)
}

func _HAService_HAStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HAServiceServer).HAStreaming(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HAService_HAStreamingServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// HAService_ServiceDesc is the grpc.ServiceDesc for HAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ha_pb.HAService",
	HandlerType: (*HAServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HAStreaming",
			Handler:       _HAService_HAStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ha.proto",
}
