// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: server.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerArbiter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ecs           bool                   `protobuf:"varint,1,opt,name=ecs,proto3" json:"ecs,omitempty"`
	Fleet         bool                   `protobuf:"varint,2,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Ha            bool                   `protobuf:"varint,3,opt,name=ha,proto3" json:"ha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerArbiter) Reset() {
	*x = PeerArbiter{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerArbiter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerArbiter) ProtoMessage() {}

func (x *PeerArbiter) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerArbiter.ProtoReflect.Descriptor instead.
func (*PeerArbiter) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *PeerArbiter) GetEcs() bool {
	if x != nil {
		return x.Ecs
	}
	return false
}

func (x *PeerArbiter) GetFleet() bool {
	if x != nil {
		return x.Fleet
	}
	return false
}

func (x *PeerArbiter) GetHa() bool {
	if x != nil {
		return x.Ha
	}
	return false
}

// 從此ha送給另外一台ha的資料 不可接收資料 （client）
type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StatusRequest_Hb
	//	*StatusRequest_IsHaConnected
	//	*StatusRequest_IsFleetConnected
	//	*StatusRequest_IsEcsConnected
	//	*StatusRequest_PeerArbiter
	Payload       isStatusRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *StatusRequest) GetPayload() isStatusRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StatusRequest) GetHb() int32 {
	if x != nil {
		if x, ok := x.Payload.(*StatusRequest_Hb); ok {
			return x.Hb
		}
	}
	return 0
}

func (x *StatusRequest) GetIsHaConnected() bool {
	if x != nil {
		if x, ok := x.Payload.(*StatusRequest_IsHaConnected); ok {
			return x.IsHaConnected
		}
	}
	return false
}

func (x *StatusRequest) GetIsFleetConnected() bool {
	if x != nil {
		if x, ok := x.Payload.(*StatusRequest_IsFleetConnected); ok {
			return x.IsFleetConnected
		}
	}
	return false
}

func (x *StatusRequest) GetIsEcsConnected() bool {
	if x != nil {
		if x, ok := x.Payload.(*StatusRequest_IsEcsConnected); ok {
			return x.IsEcsConnected
		}
	}
	return false
}

func (x *StatusRequest) GetPeerArbiter() *PeerArbiter {
	if x != nil {
		if x, ok := x.Payload.(*StatusRequest_PeerArbiter); ok {
			return x.PeerArbiter
		}
	}
	return nil
}

type isStatusRequest_Payload interface {
	isStatusRequest_Payload()
}

type StatusRequest_Hb struct {
	Hb int32 `protobuf:"varint,1,opt,name=hb,proto3,oneof"`
}

type StatusRequest_IsHaConnected struct {
	IsHaConnected bool `protobuf:"varint,2,opt,name=is_ha_connected,json=isHaConnected,proto3,oneof"`
}

type StatusRequest_IsFleetConnected struct {
	IsFleetConnected bool `protobuf:"varint,3,opt,name=is_fleet_connected,json=isFleetConnected,proto3,oneof"`
}

type StatusRequest_IsEcsConnected struct {
	IsEcsConnected bool `protobuf:"varint,4,opt,name=is_ecs_connected,json=isEcsConnected,proto3,oneof"`
}

type StatusRequest_PeerArbiter struct {
	PeerArbiter *PeerArbiter `protobuf:"bytes,5,opt,name=peer_arbiter,json=peerArbiter,proto3,oneof"`
}

func (*StatusRequest_Hb) isStatusRequest_Payload() {}

func (*StatusRequest_IsHaConnected) isStatusRequest_Payload() {}

func (*StatusRequest_IsFleetConnected) isStatusRequest_Payload() {}

func (*StatusRequest_IsEcsConnected) isStatusRequest_Payload() {}

func (*StatusRequest_PeerArbiter) isStatusRequest_Payload() {}

// 另外一台ha送來這台ha的資料 原則上不從此發送訊息到另外的ha (server)
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StatusResponse_Hb
	//	*StatusResponse_IsHaConnected
	//	*StatusResponse_IsFleetConnected
	//	*StatusResponse_IsEcsConnected
	//	*StatusResponse_PeerArbiter
	Payload       isStatusResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResponse) GetPayload() isStatusResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StatusResponse) GetHb() int32 {
	if x != nil {
		if x, ok := x.Payload.(*StatusResponse_Hb); ok {
			return x.Hb
		}
	}
	return 0
}

func (x *StatusResponse) GetIsHaConnected() bool {
	if x != nil {
		if x, ok := x.Payload.(*StatusResponse_IsHaConnected); ok {
			return x.IsHaConnected
		}
	}
	return false
}

func (x *StatusResponse) GetIsFleetConnected() bool {
	if x != nil {
		if x, ok := x.Payload.(*StatusResponse_IsFleetConnected); ok {
			return x.IsFleetConnected
		}
	}
	return false
}

func (x *StatusResponse) GetIsEcsConnected() bool {
	if x != nil {
		if x, ok := x.Payload.(*StatusResponse_IsEcsConnected); ok {
			return x.IsEcsConnected
		}
	}
	return false
}

func (x *StatusResponse) GetPeerArbiter() *PeerArbiter {
	if x != nil {
		if x, ok := x.Payload.(*StatusResponse_PeerArbiter); ok {
			return x.PeerArbiter
		}
	}
	return nil
}

type isStatusResponse_Payload interface {
	isStatusResponse_Payload()
}

type StatusResponse_Hb struct {
	Hb int32 `protobuf:"varint,1,opt,name=hb,proto3,oneof"`
}

type StatusResponse_IsHaConnected struct {
	IsHaConnected bool `protobuf:"varint,2,opt,name=is_ha_connected,json=isHaConnected,proto3,oneof"`
}

type StatusResponse_IsFleetConnected struct {
	IsFleetConnected bool `protobuf:"varint,3,opt,name=is_fleet_connected,json=isFleetConnected,proto3,oneof"`
}

type StatusResponse_IsEcsConnected struct {
	IsEcsConnected bool `protobuf:"varint,4,opt,name=is_ecs_connected,json=isEcsConnected,proto3,oneof"`
}

type StatusResponse_PeerArbiter struct {
	PeerArbiter *PeerArbiter `protobuf:"bytes,5,opt,name=peer_arbiter,json=peerArbiter,proto3,oneof"`
}

func (*StatusResponse_Hb) isStatusResponse_Payload() {}

func (*StatusResponse_IsHaConnected) isStatusResponse_Payload() {}

func (*StatusResponse_IsFleetConnected) isStatusResponse_Payload() {}

func (*StatusResponse_IsEcsConnected) isStatusResponse_Payload() {}

func (*StatusResponse_PeerArbiter) isStatusResponse_Payload() {}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\n" +
	"ha_sync_pb\"E\n" +
	"\vPeerArbiter\x12\x10\n" +
	"\x03ecs\x18\x01 \x01(\bR\x03ecs\x12\x14\n" +
	"\x05fleet\x18\x02 \x01(\bR\x05fleet\x12\x0e\n" +
	"\x02ha\x18\x03 \x01(\bR\x02ha\"\xf0\x01\n" +
	"\rStatusRequest\x12\x10\n" +
	"\x02hb\x18\x01 \x01(\x05H\x00R\x02hb\x12(\n" +
	"\x0fis_ha_connected\x18\x02 \x01(\bH\x00R\risHaConnected\x12.\n" +
	"\x12is_fleet_connected\x18\x03 \x01(\bH\x00R\x10isFleetConnected\x12*\n" +
	"\x10is_ecs_connected\x18\x04 \x01(\bH\x00R\x0eisEcsConnected\x12<\n" +
	"\fpeer_arbiter\x18\x05 \x01(\v2\x17.ha_sync_pb.PeerArbiterH\x00R\vpeerArbiterB\t\n" +
	"\apayload\"\xf1\x01\n" +
	"\x0eStatusResponse\x12\x10\n" +
	"\x02hb\x18\x01 \x01(\x05H\x00R\x02hb\x12(\n" +
	"\x0fis_ha_connected\x18\x02 \x01(\bH\x00R\risHaConnected\x12.\n" +
	"\x12is_fleet_connected\x18\x03 \x01(\bH\x00R\x10isFleetConnected\x12*\n" +
	"\x10is_ecs_connected\x18\x04 \x01(\bH\x00R\x0eisEcsConnected\x12<\n" +
	"\fpeer_arbiter\x18\x05 \x01(\v2\x17.ha_sync_pb.PeerArbiterH\x00R\vpeerArbiterB\t\n" +
	"\apayload2\\\n" +
	"\rHASyncService\x12K\n" +
	"\x0eExchangeStatus\x12\x19.ha_sync_pb.StatusRequest\x1a\x1a.ha_sync_pb.StatusResponse(\x010\x01B\x18Z\x16kenmec/ha/protoGen;genb\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_server_proto_goTypes = []any{
	(*PeerArbiter)(nil),    // 0: ha_sync_pb.PeerArbiter
	(*StatusRequest)(nil),  // 1: ha_sync_pb.StatusRequest
	(*StatusResponse)(nil), // 2: ha_sync_pb.StatusResponse
}
var file_server_proto_depIdxs = []int32{
	0, // 0: ha_sync_pb.StatusRequest.peer_arbiter:type_name -> ha_sync_pb.PeerArbiter
	0, // 1: ha_sync_pb.StatusResponse.peer_arbiter:type_name -> ha_sync_pb.PeerArbiter
	1, // 2: ha_sync_pb.HASyncService.ExchangeStatus:input_type -> ha_sync_pb.StatusRequest
	2, // 3: ha_sync_pb.HASyncService.ExchangeStatus:output_type -> ha_sync_pb.StatusResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	file_server_proto_msgTypes[1].OneofWrappers = []any{
		(*StatusRequest_Hb)(nil),
		(*StatusRequest_IsHaConnected)(nil),
		(*StatusRequest_IsFleetConnected)(nil),
		(*StatusRequest_IsEcsConnected)(nil),
		(*StatusRequest_PeerArbiter)(nil),
	}
	file_server_proto_msgTypes[2].OneofWrappers = []any{
		(*StatusResponse_Hb)(nil),
		(*StatusResponse_IsHaConnected)(nil),
		(*StatusResponse_IsFleetConnected)(nil),
		(*StatusResponse_IsEcsConnected)(nil),
		(*StatusResponse_PeerArbiter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
