// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: server.proto

package gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HASyncService_ExchangeStatus_FullMethodName = "/ha_sync_pb.HASyncService/ExchangeStatus"
)

// HASyncServiceClient is the client API for HASyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// bidirectional Streaming
type HASyncServiceClient interface {
	// Use streaming for continuous status exchange
	ExchangeStatus(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StatusRequest, StatusResponse], error)
}

type hASyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHASyncServiceClient(cc grpc.ClientConnInterface) HASyncServiceClient {
	return &hASyncServiceClient{cc}
}

func (c *hASyncServiceClient) ExchangeStatus(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StatusRequest, StatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HASyncService_ServiceDesc.Streams[0], HASyncService_ExchangeStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatusRequest, StatusResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HASyncService_ExchangeStatusClient = grpc.BidiStreamingClient[StatusRequest, StatusResponse]

// HASyncServiceServer is the server API for HASyncService service.
// All implementations must embed UnimplementedHASyncServiceServer
// for forward compatibility.
//
// bidirectional Streaming
type HASyncServiceServer interface {
	// Use streaming for continuous status exchange
	ExchangeStatus(grpc.BidiStreamingServer[StatusRequest, StatusResponse]) error
	mustEmbedUnimplementedHASyncServiceServer()
}

// UnimplementedHASyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHASyncServiceServer struct{}

func (UnimplementedHASyncServiceServer) ExchangeStatus(grpc.BidiStreamingServer[StatusRequest, StatusResponse]) error {
	return status.Error(codes.Unimplemented, "method ExchangeStatus not implemented")
}
func (UnimplementedHASyncServiceServer) mustEmbedUnimplementedHASyncServiceServer() {}
func (UnimplementedHASyncServiceServer) testEmbeddedByValue()                       {}

// UnsafeHASyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HASyncServiceServer will
// result in compilation errors.
type UnsafeHASyncServiceServer interface {
	mustEmbedUnimplementedHASyncServiceServer()
}

func RegisterHASyncServiceServer(s grpc.ServiceRegistrar, srv HASyncServiceServer) {
	// If the following call panics, it indicates UnimplementedHASyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HASyncService_ServiceDesc, srv)
}

func _HASyncService_ExchangeStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HASyncServiceServer).ExchangeStatus(&grpc.GenericServerStream[StatusRequest, StatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HASyncService_ExchangeStatusServer = grpc.BidiStreamingServer[StatusRequest, StatusResponse]

// HASyncService_ServiceDesc is the grpc.ServiceDesc for HASyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HASyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ha_sync_pb.HASyncService",
	HandlerType: (*HASyncServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExchangeStatus",
			Handler:       _HASyncService_ExchangeStatus_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server.proto",
}
